apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - image: "ghcr.io/packituz-gttz/demo:{{ .Values.image.tag }}"
          name: {{ .Values.appName }}
          {{- if ((.Values.envrironmentVariables)) }}
          env:
          {{- range $key, $value := .Values.envrironmentVariables }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}

