version: '3.0'

tasks:
  push-demo-image:
    desc: "Pushes demo image to GHCR with multiple tags"
    cmds:
      - docker build -f Dockerfile --build-arg VERSION=1.0.0 . -t ghcr.io/packituz-gttz/demo:1.0.0 -t ghcr.io/packituz-gttz/demo:v1.0
      - sleep 2
      - docker build -f Dockerfile --build-arg VERSION=2.0.0 . -t ghcr.io/packituz-gttz/demo:2.0.0 -t ghcr.io/packituz-gttz/demo:v2.0
      - sleep 2
      - docker build -f Dockerfile --build-arg VERSION=3.0.0 . -t ghcr.io/packituz-gttz/demo:3.0.0 -t ghcr.io/packituz-gttz/demo:v3.0
      - sleep 2
      - docker build -f Dockerfile --build-arg VERSION=4.0.0 . -t ghcr.io/packituz-gttz/demo:4.0.0 -t ghcr.io/packituz-gttz/demo:v4.0
      - sleep 2
      - docker build -f Dockerfile --build-arg VERSION=5.0.0 . -t ghcr.io/packituz-gttz/demo:5.0.0 -t ghcr.io/packituz-gttz/demo:v5.0
      - docker push ghcr.io/packituz-gttz/demo --all-tags