apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: gcr.io/packituz-gttz/demo:*
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-repository: git@github.com:packituz-gttz/charts-example.git
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:/gitops/img-updater-example/values.yaml"
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/demo-chart/
    repoURL: https://github.com/packituz-gttz/charts-example
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml